using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using BLL.Threats.External.Minor.Red;
using BLL.Threats.External.Minor.White;
using BLL.Threats.External.Minor.Yellow;
using BLL.Threats.External.Serious.Red;
using BLL.Threats.External.Serious.White;
using BLL.Threats.External.Serious.Yellow;
using BLL.Threats.Internal.Minor.Red;
using BLL.Threats.Internal.Minor.White;
using BLL.Threats.Internal.Minor.Yellow;
using BLL.Threats.Internal.Serious.Red;
using BLL.Threats.Internal.Serious.White;
using BLL.Threats.Internal.Serious.Yellow;

namespace BLL.Threats
{
	public class ThreatFactory
	{
		private readonly Dictionary<Type, string> threatTypesByDisplayName = new Dictionary<Type, string>
		{
			{typeof (EnergySnake), "Energy Snake"},
			{typeof (JumperB), "Jumper E3-106"},
			{typeof (JumperA), "Jumper E3-105"},
			{typeof (MegashieldFighter), "Megashield Fighter"},
			{typeof (PhasingPulser), "Phasing Pulser"},
			{typeof (PolarizedFighter), "Polarized Fighter"},
			{typeof (PhasingDestroyer), "Phasing Destroyer"},
			{typeof (PlasmaticNeedleship), "Plasmatic Needleship"},
			{typeof (SealedCapsule), "Sealed Capsule"},
			{typeof (Amoeba), "Amoeba"},
			{typeof (Gunship), "Gunship"},
			{typeof (Jellyfish), "Jellyfish"},
			{typeof (Kamikaze), "Kamikaze"},
			{typeof (Marauder), "Marauder"},
			{typeof (MegashieldDestroyer), "Megashield Destroyer"},
			{typeof (Meteoroid), "Meteoroid"},
			{typeof (MinorAsteroid), "Minor Asteroid"},
			{typeof (PhasingFighter), "Phasing Fighter"},
			{typeof (EnergyDragon), "Energy Dragon"},
			{typeof (Leaper), "Leaper"},
			{typeof (MegashieldManOfWar), "Megashield Man-Of-War"},
			{typeof (Overlord), "Overlord"},
			{typeof (Planetoid), "Planetoid"},
			{typeof (PolarizedFrigate), "Polarized Frigate"},
			{typeof (SuperCarrier), "Super-Carrier"},
			{typeof (TransmitterSatellite), "Transmitter Satellite"},
			{typeof (Asteroid), "Asteroid"},
			{typeof (CryoshieldFighter), "Cryoshield Fighter"},
			{typeof (CryoshieldFrigate), "Cryoshield Frigate"},
			{typeof (Destroyer), "Destroyer"},
			{typeof (DimensionSpider), "Dimension Spider"},
			{typeof (EnergyCloud), "Energy Cloud"},
			{typeof (Frigate), "Frigate"},
			{typeof (InterstellarOctopus), "Interstellar Octopus"},
			{typeof (LeviathanTanker), "Leviathan Tanker"},
			{typeof (Maelstrom), "Maelstrom"},
			{typeof (ManOfWar), "Man-Of-War"},
			{typeof (MiniCarrier), "Mini-Carrier"},
			{typeof (PhantomFighter), "Phantom Fighter"},
			{typeof (PlasmaticFighter), "Plasmatic Fighter"},
			{typeof (PulseBall), "Pulse Ball"},
			{typeof (PulseSatellite), "Pulse Satellite"},
			{typeof (Scout), "Scout"},
			{typeof (Behemoth), "Behemoth"},
			{typeof (Juggernaut), "Juggernaut"},
			{typeof (MajorAsteroid), "Major Asteroid"},
			{typeof (MotherSwarm), "Mother Swarm"},
			{typeof (NebulaCrab), "Nebula Crab"},
			{typeof (Nemesis), "Nemesis"},
			{typeof (PhasingManOfWar), "Phasing Man-Of-War"},
			{typeof (PhasingFrigate), "Phasing Frigate"},
			{typeof (PlasmaticFrigate), "Plasmatic Frigate"},
			{typeof (PsionicSatellite), "Psionic Satellite"},
			{typeof (SpacecraftCarrier), "Spacecraft Carrier"},
			{typeof (SpinningSaucer), "Spinning Saucer"},
			{typeof (StealthFighter), "Stealth Fighter"},
			{typeof (Swarm), "Swarm"},
			{typeof (BreachedAirlock), "Breached Airlock"},
			{typeof (Driller), "Driller"},
			{typeof (LateralLaserJam), "Lateral Laser Jam"},
			{typeof (PhasingTroopersB), "Phasing Troopers I3-105"},
			{typeof (PhasingTroopersA), "Phasing Troopers I3-106"},
			{typeof (PulseCannonShortCircuit), "Pulse Cannon Short Circuit"},
			{typeof (ReversedShields), "Reversed Shields"},
			{typeof (Ninja), "Ninja"},
			{typeof (OverheatedReactor), "Overheated Reactor"},
			{typeof (PowerPackOverload), "Power Pack Overload"},
			{typeof (SlimeA), "Slime I2-01"},
			{typeof (SlimeB), "Slime I2-02"},
			{typeof (TroopersA), "Troopers I2-04"},
			{typeof (TroopersB), "Troopers I2-03"},
			{typeof (Virus), "Virus"},
			{typeof (CyberGremlin), "Cyber Gremlin"},
			{typeof (HiddenTransmitterB), "Hidden Transmitter SI3-102"},
			{typeof (HiddenTransmitterA), "Hidden Transmitter SI3-103"},
			{typeof (Parasite), "Cyber Gremlin"},
			{typeof (RabidBeast), "Rabid Beast"},
			{typeof (Siren), "Siren"},
			{typeof (SpaceTimeVortex), "Space Time Vortex"},
			{typeof (Alien), "Alien"},
			{typeof (BattleBotUprising), "BattleBot Uprising"},
			{typeof (CentralLaserJam), "Central Laser Jam"},
			{typeof (CommandosB), "Commandos SI1-02"},
			{typeof (CommandosA), "Commandos SI1-01"},
			{typeof (CrossedWires), "Crossed Wires"},
			{typeof (Fissure), "Fissure"},
			{typeof (HackedShieldsA), "Hacked Shields I1-06"},
			{typeof (HackedShieldsB), "Hacked Shields I1-05"},
			{typeof (SaboteurA), "Saboteur I1-04"},
			{typeof (SaboteurB), "Saboteur I1-03"},
			{typeof (Contamination), "Contamination"},
			{typeof (Executioner), "Executioner"},
			{typeof (NuclearDevice), "Nuclear Device"},
			{typeof (PhasingAnomaly), "Phasing Anomaly"},
			{typeof (PhasingMineLayer), "Phasing Mine Layer"},
			{typeof (PowerSystemOverload), "Power System Overload"},
			{typeof (Seeker), "Seeker"},
			{typeof (Shambler), "Shambler"},
			{typeof (SkirmishersA), "Skirmishers I1-01"},
			{typeof (SkirmishersB), "Skirmishers I1-02"},
			{typeof (UnstableWarheads), "Unstable Warheads"},
			{typeof (ArmoredGrappler), "Armored Grappler"},
			{typeof (Fighter), "Fighter"}
		};

		private readonly IDictionary<Type, string> threatTypesById = new Dictionary<Type, string>
		{
			{typeof (EnergySnake), "E3-109"},
			{typeof (JumperB), "E3-106"},
			{typeof (JumperA), "E3-105"},
			{typeof (MegashieldFighter), "E3-104"},
			{typeof (PhasingPulser), "E3-102"},
			{typeof (PolarizedFighter), "E3-108"},
			{typeof (PhasingDestroyer), "E3-103"},
			{typeof (PlasmaticNeedleship), "E3-101"},
			{typeof (SealedCapsule), "E3-107"},
			{typeof (Amoeba), "E1-09"},
			{typeof (Gunship), "E1-05"},
			{typeof (Jellyfish), "E2-05"},
			{typeof (Kamikaze), "E2-01"},
			{typeof (Marauder), "E2-06"},
			{typeof (MegashieldDestroyer), "E2-103"},
			{typeof (Meteoroid), "E1-10"},
			{typeof (MinorAsteroid), "E2-07"},
			{typeof (PhasingFighter), "E2-102"},
			{typeof (EnergyDragon), "SE3-108"},
			{typeof (Leaper), "SE3-106"},
			{typeof (MegashieldManOfWar), "SE3-102"},
			{typeof (Overlord), "SE3-105"},
			{typeof (Planetoid), "SE3-107"},
			{typeof (PolarizedFrigate), "SE3-109"},
			{typeof (SuperCarrier), "SE3-103"},
			{typeof (TransmitterSatellite), "SE3-104"},
			{typeof (Asteroid), "SE1-08"},
			{typeof (CryoshieldFighter), "E1-06"},
			{typeof (CryoshieldFrigate), "SE1-05"},
			{typeof (Destroyer), "E1-02"},
			{typeof (DimensionSpider), "SE1-102"},
			{typeof (EnergyCloud), "E1-04"},
			{typeof (Frigate), "SE1-01"},
			{typeof (InterstellarOctopus), "SE1-06"},
			{typeof (LeviathanTanker), "SE1-03"},
			{typeof (Maelstrom), "SE1-07"},
			{typeof (ManOfWar), "SE1-02"},
			{typeof (MiniCarrier), "E2-101"},
			{typeof (PhantomFighter), "E2-03"},
			{typeof (PlasmaticFighter), "E1-101"},
			{typeof (PulseBall), "E1-01"},
			{typeof (PulseSatellite), "SE1-04"},
			{typeof (Scout), "E2-02"},
			{typeof (Behemoth), "SE2-01"},
			{typeof (Juggernaut), "SE2-02"},
			{typeof (MajorAsteroid), "SE2-06"},
			{typeof (MotherSwarm), "SE2-103"},
			{typeof (NebulaCrab), "SE2-04"},
			{typeof (Nemesis), "SE2-05"},
			{typeof (PhasingManOfWar), "SE3-101"},
			{typeof (PhasingFrigate), "SE2-102"},
			{typeof (PlasmaticFrigate), "SE2-101"},
			{typeof (PsionicSatellite), "SE2-03"},
			{typeof (SpacecraftCarrier), "SE1-101"},
			{typeof (SpinningSaucer), "E1-102"},
			{typeof (StealthFighter), "E1-03"},
			{typeof (Swarm), "E2-04"},
			{typeof (BreachedAirlock), "I3-104"},
			{typeof (Driller), "I3-107"},
			{typeof (LateralLaserJam), "I3-101"},
			{typeof (PhasingTroopersB), "I3-105"},
			{typeof (PhasingTroopersA), "I3-106"},
			{typeof (PulseCannonShortCircuit), "I3-102"},
			{typeof (ReversedShields), "I3-103"},
			{typeof (Ninja), "I2-102"},
			{typeof (OverheatedReactor), "I2-06"},
			{typeof (PowerPackOverload), "I2-101"},
			{typeof (SlimeA), "I2-01"},
			{typeof (SlimeB), "I2-02"},
			{typeof (TroopersA), "I2-04"},
			{typeof (TroopersB), "I2-03"},
			{typeof (Virus), "I2-05"},
			{typeof (CyberGremlin), "SI3-106"},
			{typeof (HiddenTransmitterB), "SI3-102"},
			{typeof (HiddenTransmitterA), "SI3-103"},
			{typeof (Parasite), "SI3-107"},
			{typeof (RabidBeast), "SI3-101"},
			{typeof (Siren), "SI3-105"},
			{typeof (SpaceTimeVortex), "SI3-104"},
			{typeof (Alien), "SI1-03"},
			{typeof (BattleBotUprising), "SI1-06"},
			{typeof (CentralLaserJam), "I1-101"},
			{typeof (CommandosB), "SI1-02"},
			{typeof (CommandosA), "SI1-01"},
			{typeof (CrossedWires), "SI1-05"},
			{typeof (Fissure), "SI1-04"},
			{typeof (HackedShieldsA), "I1-06"},
			{typeof (HackedShieldsB), "I1-05"},
			{typeof (SaboteurA), "I1-04"},
			{typeof (SaboteurB), "I1-03"},
			{typeof (Contamination), "SI2-04"},
			{typeof (Executioner), "SI2-01"},
			{typeof (NuclearDevice), "SI2-05"},
			{typeof (PhasingAnomaly), "SI2-101"},
			{typeof (PhasingMineLayer), "SI2-102"},
			{typeof (PowerSystemOverload), "SI2-03"},
			{typeof (Seeker), "SI2-02"},
			{typeof (Shambler), "SI1-101"},
			{typeof (SkirmishersA), "I1-01"},
			{typeof (SkirmishersB), "I1-02"},
			{typeof (UnstableWarheads), "I1-07"},
			{typeof (ArmoredGrappler), "E1-08"},
			{typeof (Fighter), "E1-07"}
		};
	}
}
